### ISSUE TITLE
Embedding R Shiny Application and Responsive iFrame

### ISSUE THREAD

**Issue by ghost** [alfaproject/ng-iframe-resizer#5]
I would like to embed an R Shiny application within a website that I am developing, which can be done by use of an iframe element.  However, I'd like the iframe height to adjust in a responsive manner to the application's content.  So as the user toggles hidden elements within the R Shiny application the iframe resizes itself accordingly.  I'm not sure if ng-iframe-resizer can handle that, but at least it should be able to resize an iframe's height upon loading the initial R Shiny application.  I followed the instructions and modified the R Shiny application from [here](https://github.com/rstudio/shiny-examples/tree/master/087-crandash), so that the original iframeResizer.contentWindow.min.js was included within the source page within the iframe (I uploaded that app to shinyapps.io so that I could include it within an iframe).  I also put together an example website ([example.zip](https://github.com/alfaproject/ng-iframe-resizer/files/2203050/example.zip)) to illustrate the issue (simply unzip the folder and open the index.html in Firefox and click on the App tab in the navbar).  The iframe does get resized a bit, but a decent amount of the application is still hidden.  Am I doing something wrong or is it a bug?

**Comment by alfaproject** [comment]
I'm not sure, but this is just an AngularJS wrapper for [iFrame Resizer](https://github.com/davidjbradshaw/iframe-resizer).

There's no logic whatsoever in this project. Maybe you should create an issue in the linked project.

**Comment by ghost** [comment]
Ok, will do.  Thanks!
